/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#bdc9c8',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#879392',
        'outline-variant': '#3e4949',
        'surface-tint': '#76d6d5',
        primary: '#76d6d5',
        'on-primary': '#003737',
        'primary-container': '#008080',
        'on-primary-container': '#e3fffe',
        'inverse-primary': '#006a6a',
        secondary: '#c8c6c5',
        'on-secondary': '#303030',
        'secondary-container': '#474746',
        'on-secondary-container': '#b7b5b4',
        tertiary: '#ffb692',
        'on-tertiary': '#552000',
        'tertiary-container': '#a96039',
        'on-tertiary-container': '#fff9f7',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#93f2f2',
        'primary-fixed-dim': '#76d6d5',
        'on-primary-fixed': '#002020',
        'on-primary-fixed-variant': '#004f4f',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1b1b1c',
        'on-secondary-fixed-variant': '#474746',
        'tertiary-fixed': '#ffdbcb',
        'tertiary-fixed-dim': '#ffb692',
        'on-tertiary-fixed': '#341100',
        'on-tertiary-fixed-variant': '#733512',
        background: '#131313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353534',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        jetbrainsMono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        'container-padding': '1.5rem',
        'element-gap': '0.75rem',
        'stack-tight': '0.25rem',
        gutter: '1rem',
      },
    },
  },
  plugins: [],
}
